name: Check AWS Credentials

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch
  pull_request:
    branches:
      - main  # Trigger on pull requests to the main branch

permissions:
  id-token: write  # Required for OIDC
  contents: read   # Required to checkout the repository

jobs:
  check-aws-credentials:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }} # IAM role ARN
          aws-region: ${{ secrets.AWS_ACCOUNT_ID }}  # AWS region 

      - name: Verify AWS credentials
        run: |
          # Check if AWS CLI is working and credentials are valid
          aws sts get-caller-identity