name: Test EC2 SSH Connection

on:
  push: # Trigger on pushes (or use workflow_dispatch for manual runs)
    branches:
      - main # Or your main branch name

jobs:
  test-ssh:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code (optional)
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: SSH to EC2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu # Or your username
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            echo "Successfully connected to EC2!"
            whoami
            hostname
            uptime
            date
            # Check for Docker (if needed)
            if command -v docker &> /dev/null; then
              echo "Docker is installed:"
              docker ps
            else
              echo "Docker is NOT installed."
            fi
            # Check if your application is running (replace with your app's port)
            if curl -s http://localhost:8080 > /dev/null; then # Replace 8080 with your app's port
              echo "Application is running!"
            else
              echo "Application is NOT running or not accessible on port 8080." # Replace 8080
            fi
            # Add more debugging commands as needed